server:
  port: 8084

spring:
  application:
    name: product-catalog-query-api
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/product-catalog-read}

logging:
  level:
    com.ecommerce: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
